name: Test Keystore

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Decode keystore
        run: |
          printf "%s" "${{ secrets.KEYSTORE }}" | base64 --decode > my-release-key.jks

      - name: Verify keystore
        run: |
          keytool -list -v \
            -keystore my-release-key.jks \
            -storepass "${{ secrets.KEYSTORE_PASSWORD }}"
